version: '3.8'
services:
  bot:
    build: .
    environment:
      BOT_TOKEN: "${BOT_TOKEN}"
      ADMIN_ID: "${ADMIN_ID}"
      GROUP_ID: "${GROUP_ID}"
      DEEPSEEK_API_KEY: "${DEEPSEEK_API_KEY}"
    volumes:
      - ./data:/app/data
