version: '3.8'
services:
  redis:
    image: redis:7-alpine
    restart: always
  bot:
    build: .
    depends_on:
      - redis
    environment:
      BOT_TOKEN: ""
      ADMIN_ID: ""
      DEEPSEEK_API_KEY: ""
      GROUP_IDS: ""
    volumes:
      - ./data:/app/data
